---
title: "R0Beta"
author: "Pierre Nouvellet"
date: "2019-07"
output:
  html_document:
    self_contained: no
---

```{r , include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_tD_Over/figs/', fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

```

# input data


```{r}


source(file = '../inputProcessing/date_input.r')

rep <- 1e4
rep_sim <- 1e3

for (date_num in length(dates_input)){#1:length(dates_input)){
  # date_num = length(dates_input)
  
  date_week_finishing <-  as.Date(dates_input[date_num],format = '%Y-%m-%d')
  output <- list()
  output2 <- list()
  
  for (Mdata in c('A','G')){
    # Mdata = 'A'
    
    inputs<- readRDS(file=paste0(
      '../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/inputProcessing/Rdata/',
      date_week_finishing,'_inputs_from_',Mdata,'.rds'))
    
    for (si in 1:2){
    #   si=2
      
      ########################################
      ####inputs
      D <- inputs$D
      M <- inputs$M
      Ot <- inputs$Ot[[si]]$Ot
      W <- inputs$W[[si]]$W
      H <- inputs$H
      SI <- inputs$SI[[si]]$SI
      delta_id <- inputs$delta_id
      #
      country <- names(D)[-1]
      
      mD <- as.matrix(D[,-1])
      N_geo <- ncol(D)-1
      N_days <- nrow(D)
      
      N_week <- nrow(D)/7
      
      # prerp MCMC
      # epi
      R0 <- 5
      # for risk
      b <- 0
      o <- 1
      
      min_t_change <- which(as.character(D$dates) %in% c('2020-04-01'))
      max_t_change <- nrow(D)-7*6
      t_change <- round((min_t_change+max_t_change)/2)
      
      ####################################################
      ############ improve prior for t_change ############
      min_t_change <- rep(NA,N_geo)
      for (i in 1:N_geo){
        min_t_change[i] <- (which(M[,i] == min(M[,i]))+3*7)[1]
      }
      max_t_change <- min_t_change + 4*7
      f <- which(max_t_change > (nrow(D)-7*4))
      max_t_change[f] <- nrow(D)-7*4
      f_remove <- which(min_t_change > max_t_change)
      max_t_change[f_remove] <- nrow(D)
     
      t_change <- round((min_t_change+max_t_change)/2)
      
      ####################################################
      
      theta0 <- c(rep(R0,N_geo),
                  rep(b,N_geo),
                  rep(R0,N_geo),
                  rep(b,N_geo),
                  t_change,
                  rep(o,N_geo))
      
      prior_theta <- matrix(c(rep(c(0,5),N_geo),
                              rep(c(-1e2,1e2),N_geo),
                              rep(c(0,5),N_geo),
                              rep(c(-1e2,1e2),N_geo),
                              c(rbind(min_t_change,max_t_change)), # rep(c(min_t_change,max_t_change),N_geo), # t_change
                              rep(c(0,1e5),N_geo)), # over
                            length(theta0),2, byrow=TRUE)
      
      # parameter names
      f0 <- function(x) paste0('R0_',x)
      f1 <- function(x) paste0('beta_',x)
      f2 <- function(x) paste0('R02_',x)
      f3 <- function(x) paste0('beta2_',x)
      f4 <- function(x) paste0('tchange_',x)
      f5 <- function(x) paste0('Over_',x)
      n_t<- c(sapply(country,f0),
              sapply(country,f1), 
              sapply(country,f2),
              sapply(country,f3),
              sapply(country,f4),sapply(country,f5))
      
      # sd dev for proposal
      sigma <- rep(1e-1,length(theta0))
      sigma[(5-1)*N_geo+(1:N_geo)] <- 10
      
      ########################################
      # useful functions
      # useful functions
      sapply(paste0('Rscript/with_Tchange/',(list.files('Rscript/with_Tchange/'))),FUN = source)
      
      ########################################
      #run MCMC
      
      #check
      # res <- MCMC_iter(iter = rep, theta0 = theta0, s = sigma)
      res <- MCMC_full(iter = rep, 
                       theta0 = theta0,
                       s = sigma, 
                       repli_adapt = 10, 
                       within_iter = rep/10)
      res$DIC[f_remove] <- NA
      ########################################
      ## check convergence
      
      print('########################################')
      print(paste0('check convergence',date_week_finishing,' - ',Mdata,' - ',si)) 
      
      
      Acc <- colSums(diff(res$theta)!=0)/(rep-1)
      
      # thining
      if(rep >1e3){
        f <- round(seq(1,rep,length.out = 1e3))
        res$theta <- res$theta[f,]
        res$logL <- res$logL[f,]
      }
      rep <- nrow(res$theta)
      
      
      plot(res$logL[,1],main=paste0('DIC ',res$DIC[1],', P ',res$DIC[2]))
      layout(matrix(1:4,2,2))
      for (i in 1:length(theta0)){
        plot(res$theta[,i],
             main = paste0(n_t[i],' - ',round(Acc[i]*100)))#,       ylim = prior_theta[i,])
      }
      
      # apply(res$theta,2,quantile,c(.5,.025,.975))
      
      
      ncountry <- country
      ncountry[which(ncountry %in% 'United_Kingdom')] <- 'UK'
      ncountry[which(ncountry %in% 'United_States_of_America')] <- 'USA'
      
      R0s <- apply(res$theta[,1:N_geo],2,quantile,c(.5,.025,.975))
      betas <- apply(res$theta[,N_geo+(1:N_geo)],2,quantile,c(.5,.025,.975))
      R0s2 <- apply(res$theta[,2*N_geo+(1:N_geo)],2,quantile,c(.5,.025,.975))
      betas2 <- apply(res$theta[,3*N_geo+(1:N_geo)],2,quantile,c(.5,.025,.975))
      tchange <- apply(res$theta[,4*N_geo+(1:N_geo)],2,quantile,c(.5,.025,.975))
      over <- apply(res$theta[,5*N_geo+(1:N_geo)],2,quantile,c(.5,.025,.975))
      
      ## margin for side 2 is 7 lines in siz
      layout(1)
      par(mar = c(7,4,4,2) + 0.1) ## default is c(5,4,4,2) + 0.1
      
      errbar(1:N_geo-.2,R0s[1,],R0s[2,],R0s[3,],
             xlab = '', ylab = TeX('R_0'), bty = 'n',xaxt = "n",ylim=c(0,5))
      errbar(1:N_geo+.2,R0s2[1,],R0s2[2,],R0s2[3,],col= 'red3',add=TRUE,
             xlab = '', ylab = TeX('R_0'), bty = 'n',xaxt = "n",ylim=c(0,5))
     
      
      lines(c(1,N_geo),rep(1,2), col = 'red')
      
      axis(1, at=1:N_geo, labels=ncountry,las=2)
      
      ####
      errbar(1:N_geo-.2,betas[1,],betas[2,],betas[3,],
             xlab = '', ylab = TeX('$\\beta$'), bty = 'n',xaxt = "n")
      errbar(1:N_geo+.2,betas2[1,],betas2[2,],betas2[3,],col='red3',add=TRUE,
             xlab = '', ylab = TeX('$\\beta$'), bty = 'n',xaxt = "n")
      axis(1, at=1:N_geo, labels=ncountry,las=2)
      
           ####
      errbar(1:N_geo,tchange[1,],tchange[2,],tchange[3,],
             xlab = '', ylab = TeX('t_change'), bty = 'n',xaxt = "n")
      
      axis(1, at=1:N_geo, labels=ncountry,las=2)
      
      
      output[[si]] <- list(resMCMC = res,
                           R0s =R0s,
                           betas = betas, 
                           R0s2 = R0s2 ,
                           betas2 = betas2,
                           tchange = tchange,
                           over = over
      )
      
      
 #################################### 
      ## Rt daily and Rt_D2
      ### observed mobility
      
      res_m <- output[[si]]
      rep <- nrow(res_m$resMCMC$theta)
      Rt_daily <- array(NA,dim = c(N_days,N_geo,rep))
      Rt_D2 <- Rt_daily
      m_eff <- Rt_daily
      
      
      f_m_eff <- function(){
        1 + 1/B * log( inputs$H %*% exp( - B * (1-inputs$M) ) )
      }
      
      
      for (j in 1:rep){
        R_daily <- Rt_fun(theta = res_m$resMCMC$theta[j,], x = inputs$M )
        Rt_daily[,,j] <- R_daily
        Rt_D2[,,j] <- inputs$H %*% R_daily
        
        B <- rep(1,nrow(inputs$M)) %*% t(res_m$resMCMC$theta[j,(2-1)*N_geo+ (1:N_geo)])
        for (i in 1:N_geo){
          B[ (res_m$resMCMC$theta[(5-1)*N_geo+ (i) ]): nrow(inputs$M) ,i] <- res_m$resMCMC$theta[(4-1)*N_geo+ (i)]
        }
        m_eff[,,j] <- f_m_eff() # 1 + 1/B * log( inputs$H %*% exp( - B * (1-inputs$M) ) )
      }
      
      ###################################
      ### assumed mobility
      
      
      n_d <- 1e3
      Rt_assumed_mob1 <- array(NA,dim = c(n_d,N_geo,rep))
      Rt_assumed_mob2 <- array(NA,dim = c(n_d,N_geo,rep))
      x <-  matrix(seq(0,1,length.out = n_d),n_d,N_geo,byrow = FALSE)
      
      
      for (j in 1:rep){
        # R0/beta for first period
        new_theta1 <- res_m$resMCMC$theta[j,]
        new_theta1[(3-1)*N_geo+ (1:N_geo)] <- new_theta1[(1-1)*N_geo+ (1:N_geo)] 
        new_theta1[(4-1)*N_geo+ (1:N_geo)] <- new_theta1[(2-1)*N_geo+ (1:N_geo)] 
         # R0/beta for 2nd period
        new_theta2 <- res_m$resMCMC$theta[j,]
        new_theta2[(1-1)*N_geo+ (1:N_geo)] <- new_theta2[(3-1)*N_geo+ (1:N_geo)] 
        new_theta2[(2-1)*N_geo+ (1:N_geo)] <- new_theta2[(4-1)*N_geo+ (1:N_geo)] 
        
        R_daily <- Rt_fun(theta = new_theta1, x = 1-x )
        Rt_assumed_mob1[,,j] <- R_daily
        
        R_daily <- Rt_fun(theta = new_theta2, x = 1-x )
        Rt_assumed_mob2[,,j] <- R_daily
      }
      
      
      
      #####################################
      ## summaries
      
      ### Summary for Rt daily and Rt_D2
      
      
      
      # format outputs
      temp <- D
      temp[,-1] <- NA
      
      results_full_Rt_daily <- list(median_R = temp,
                                    low_R = temp,
                                    up_R = temp,
                                    M = temp)
      
      results_full_Rt_D2 <- list(median_R = temp,
                                 low_R = temp,
                                 up_R = temp,
                                 M_D = temp)
      
      results_meff <- list(median_meff = temp,
                           low_meff = temp,
                           up_meff = temp)
      
      for (i in 1:N_geo){
        
        temp <- apply(Rt_daily[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
        results_full_Rt_daily$median_R[,i+1] <- temp[1,]
        results_full_Rt_daily$low_R[,i+1] <- temp[2,]
        results_full_Rt_daily$up_R[,i+1] <- temp[3,]
        results_full_Rt_daily$M[,i+1] <- M[,i]
        
        temp <- apply(Rt_D2[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
        results_full_Rt_D2$median_R[,i+1] <- temp[1,]
        results_full_Rt_D2$low_R[,i+1] <- temp[2,]
        results_full_Rt_D2$up_R[,i+1] <- temp[3,]
        # results_full_Rt_D2$M_D[,i+1] <- M_D[,i]
        
        temp <- apply(m_eff[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
        results_meff$median_meff[,i+1] <- temp[1,]
        results_meff$low_meff[,i+1] <- temp[2,]
        results_meff$up_meff[,i+1] <- temp[3,]
        
        
      }
      
      
      #############################################
      ### Summary for Rt assumed mobility
      
      
      
      # format outputs
      temp <- data.frame(matrix(NA,nrow = n_d, ncol = 1+N_geo))
      temp[,1] <- x[,1]
      names(temp) <- c('mobility', country)
      
      results_full_Rt_assumed_mob1 <- list(median_R = temp,
                                          low_R = temp,
                                          up_R = temp)
      
      results_full_Rt_assumed_mob2 <- list(median_R = temp,
                                          low_R = temp,
                                          up_R = temp)
      
      Thresholds1 <- output[[si]]$R0s
      Thresholds2 <- output[[si]]$R0s
      f <- c()
      for (i in 1:N_geo){
        # first period
        temp <- apply(Rt_assumed_mob1[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
        results_full_Rt_assumed_mob1$median_R[,i+1] <- temp[1,]
        results_full_Rt_assumed_mob1$low_R[,i+1] <- temp[2,]
        results_full_Rt_assumed_mob1$up_R[,i+1] <- temp[3,]
        
        f[1] <- which(results_full_Rt_assumed_mob1$median_R[,i+1] < 1)[1]
        f[2] <- which(results_full_Rt_assumed_mob1$low_R[,i+1] < 1)[1]
        f[3] <- which(results_full_Rt_assumed_mob1$up_R[,i+1] < 1)[1]
        for(j in 1:3){
          if (is.na(f[j])){
            Thresholds1[j,i] <- NA
          }else{
            Thresholds1[j,i] <-mean(results_full_Rt_assumed_mob1$median_R$mobility[f[j]:(f[j]+1)])
          }
        }
        
        # 2nd period
        temp <- apply(Rt_assumed_mob2[,i,],1,quantile,c(.5,.025,.975),na.rm = TRUE)
        results_full_Rt_assumed_mob2$median_R[,i+1] <- temp[1,]
        results_full_Rt_assumed_mob2$low_R[,i+1] <- temp[2,]
        results_full_Rt_assumed_mob2$up_R[,i+1] <- temp[3,]
        
        f[1] <- which(results_full_Rt_assumed_mob2$median_R[,i+1] < 1)[1]
        f[2] <- which(results_full_Rt_assumed_mob2$low_R[,i+1] < 1)[1]
        f[3] <- which(results_full_Rt_assumed_mob2$up_R[,i+1] < 1)[1]
        for(j in 1:3){
          if (is.na(f[j])){
            Thresholds2[j,i] <- NA
          }else{
            Thresholds2[j,i] <-mean(results_full_Rt_assumed_mob2$median_R$mobility[f[j]:(f[j]+1)])
          }
        }
      }
     output[[si]]$Thresholds <- Thresholds1
     output[[si]]$Thresholds2 <- Thresholds2
     
     
      #############################################
      # forecast and predictions
      
      ## short-term
      n_pred <- 7
      # choose future mobility
      M_pred <- rbind(M,matrix(M[nrow(M),],n_pred,N_geo,byrow = TRUE))
      # useful functions
      sapply(paste0('Rscript/proj_f/',(list.files('Rscript/proj_f'))),FUN = source)
      res_projection_ST <- mobility_prediction_over2(n_pred = n_pred, rep_sim = rep_sim)
      
      ## summary
      
      temp <- data.frame(dates = seq(1,n_pred) + D$dates[nrow(D)],
                         matrix(NA,n_pred,N_geo))
      names(temp) <- c('dates',country)
      summary_proj <- list(median = temp,
                           low = temp,
                           up = temp)
      for (i in 1:N_geo){
        temp <- apply(res_projection_ST$D_pred[,i,],1,quantile,c(.5,.025,.975))
        summary_proj$median[,i+1] <- temp[1,]
        summary_proj$low[,i+1] <- temp[2,]
        summary_proj$up[,i+1] <- temp[3,]
      }
      
      
      output2[[si]] <- list(results_full_Rt_daily = results_full_Rt_daily,
                            results_full_Rt_D2 = results_full_Rt_D2,
                            results_meff = results_meff,
                            results_full_Rt_assumed_mob = results_full_Rt_assumed_mob1,
                            results_full_Rt_assumed_mob2 = results_full_Rt_assumed_mob2,
                            summary_proj_ST = summary_proj)
      
    }
    
    saveRDS(object = output,
            file = paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_tD_Over/Rdata/',
                          date_week_finishing,'_output_over_form_',Mdata,'.rds' ))
    
    saveRDS(object = output2,
            file = paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_tD_Over/Rdata/',
                          date_week_finishing,'_output2_over_form_',Mdata,'.rds' ))
  }
}

```
