---
title: "input"
author: "Pierre Nouvellet"
date: "2019-07"
output:
  html_document:
    self_contained: no
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)
library(tidyr)

opts_chunk$set(collapse = TRUE)
path_s <- '../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/'

opts_chunk$set(fig.path=paste0(path_s,'inputs/figs/'), fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )



```

# input data


load and clean mobility data.

```{r, echo = FALSE}

d_m <- read.csv(file=paste0(path_s,'inputs/applemobilitytrends-2020-10-24.csv'),
                            stringsAsFactors = FALSE)

	

d_m <- d_m[which(d_m$geo_type %in% 'country/region'),]
d_m <- d_m[,-which(names(d_m) %in% c("alternative_name", "sub.region", "country"))]
tail(names(d_m))
```


```{r}

d_g <- read.csv(file=paste0(path_s,'inputs/Global_Mobility_Report.csv'),
                stringsAsFactors = FALSE)

d_g <- d_g[ which(d_g$sub_region_1 == ''),]
d_g <- d_g[ which(d_g$sub_region_2 == ''),]
d_g <- d_g[ which(d_g$metro_area == ''),]

names(d_g)
##

a <- tidyr::gather(d_g, var,
                   val,
                   `retail_and_recreation_percent_change_from_baseline`:
                     `residential_percent_change_from_baseline`)
b <- tidyr::spread(a, date, val)


b <- b[,-which(names(b) %in% c("sub_region_1","sub_region_2" , 'metro_area','iso_3166_2_code','census_fips_code'))]
# b <- b[-which(b$var %in% c('grocery_and_pharmacy_percent_change_from_baseline',
#                                'parks_percent_change_from_baseline',
#                                'residential_percent_change_from_baseline')) , ]

names(b)[1:3] <- names(d_m)[1:3]

b[,-c(1:3)] <- b[,-c(1:3)]+100
names(b)[-c(1:3)] <- sub(x=paste0('X',sub(x =names(b)[-c(1:3)],pattern = '-',replacement = '.')),
                         pattern = '-',replacement = '.')

d_g <- b
tail(names(d_g))

# trim datasets
d_g <- d_g[,1:which(names(d_g) %in% 'X2020.09.13')]
d_m <- d_m[,1:which(names(d_m) %in% 'X2020.09.13')]
tail(names(d_g))
tail(names(d_m))

d_g <- d_g[,-c(4:which(names(d_g) %in% "X2020.02.16"))]
d_m <- d_m[,-c(4:which(names(d_m) %in% "X2020.02.16"))]
head(names(d_g))
head(names(d_m))
# d_g <- d_g[,-which(names(d_g) %in% c('X2020.02.15','X2020.02.16'))]
# range(d_g[,-c(1:3)],na.rm=TRUE)

# d_g <- cbind(d_g,d_g[,'X2020.05.09'])
# names(d_g)[ncol(d_g)] <- 'X2020.05.10'
mobility_raw <- list(apple = d_m,
                     google = d_g)
saveRDS(object = mobility_raw, file = paste0(path_s,'inputs/mobility_raw.rds'))
```

