---
title: "input"
author: "Pierre Nouvellet"
date: "2019-07"
output:
  html_document:
    self_contained: no
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)

opts_chunk$set(collapse = TRUE)

path_s <- '../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/'

opts_chunk$set(fig.path=paste0(path_s,'inputProcessing/figs/'), fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

sapply(paste0('../Rfunction_library/pre_MCMC/',
              (list.files('../Rfunction_library/pre_MCMC/'))),FUN = source)

```

# input data

## load Epi and mobility data

```{r}
# date_week_finishing <-  as.Date('10/05/2020',format = '%d/%m/%Y')
# si <- 2

d <- readRDS(file=paste0(path_s,'/inputs/data_',date_week_finishing,'.rds'))
#
country <- as.character(d$Country)
# mean sd of ditrivution infection to death
mu_id = 18.8
si_std = .45*mu_id


```



load and clean mobility data.

```{r, echo = FALSE}


#miss-spelled
country[-which(as.character(country) %in% as.character(d_m$region))]

# missing for apple: Algeria, China, Dominican_Republic, Ecuador, Iran, Peru, South_Korea, 
#corrections to match name in ECDC data
d_m$region[which(d_m$region %in% 'Czech Republic')] <- 'Czechia'
d_m$region[which(d_m$region %in% 'UK')] <- 'United_Kingdom'
d_m$region[which(d_m$region %in% 'United States')] <- 'United_States_of_America'
d_m$region[which(d_m$region %in% 'United Arab Emirates')] <- 'United_Arab_Emirates'
d_m$region[which(d_m$region %in% 'South Africa')] <- 'South_Africa'
d_m$region[which(d_m$region %in% 'Saudi Arabia')] <- 'Saudi_Arabia'
d_m$region[which(d_m$region %in% 'Republic of Korea')] <- 'South_Korea'
################

# same correction for google
d_m$region[which(d_m$region %in% 'United Kingdom')] <- 'United_Kingdom'
d_m$region[which(d_m$region %in% 'United States')] <- 'United_States_of_America'
d_m$region[which(d_m$region %in% 'South Korea')] <- 'South_Korea'
d_m$region[which(d_m$region %in% 'South Africa')] <- 'South_Africa'
d_m$region[which(d_m$region %in% 'Saudi Arabia')] <- 'Saudi_Arabia'
d_m$region[which(d_m$region %in% 'United Arab Emirates')] <- 'United_Arab_Emirates'
d_m$region[which(d_m$region %in% 'Dominican Republic')] <- 'Dominican_Republic'


#miss-spelled
country[-which(as.character(country) %in% as.character(d_m$region))]

# check
if (length(country[-which(country %in% d_m$region)])>0){
  print('warning')
  country[-which(country %in% d_m$region)]
}

# include country with data in both dataset
f1 <- which(country %in% d_m$region)
f2 <- which(d_m$region %in% country)

d_m <- d_m[f2,]

d$I_active_transmission <- d$I_active_transmission[,c(1,f1+1)]
d$D_active_transmission <- d$D_active_transmission[,c(1,f1+1)]
d$Country <- d$Country[f1]

# include dates with data in both
dates <- as.Date(substr(names(d_m[,-c(1:3)]),start = 2, stop = 11),format='%Y.%m.%d')
f1 <- which(d$I_active_transmission$dates %in% dates)
f2 <- which(dates %in% d$I_active_transmission$dates)

d_m <- d_m[,c(1,2,3,3+f2)]

d$I_active_transmission <- d$I_active_transmission[f1,]
d$D_active_transmission <- d$D_active_transmission[f1,]

```



# useful data

```{r}
# correct epi
D <- d$D_active_transmission
mD <- as.matrix(D[,-1])
I <- d$I_active_transmission

cumD <- data.frame(D$dates,apply(D[,-1],2,cumsum))
cumI <- data.frame(I$dates,apply(I[,-1],2,cumsum))

N_geo <- ncol(D)-1
N_days <- nrow(D)
country <- as.character(d$Country)

```


## process mobility data

load data (dots), get weekly average, interpolate between (blue line)

```{r, echo = FALSE}

mobility <- process_mobility(d_m = d_m)


layout(matrix(1:4,2,2))
for (i  in 1:N_geo){
  plot(mobility$mob_raw$dates,mobility$mob_raw[,i+1],main = country[i],ylim = c(0,1),
       xlab = '',ylab = 'prop. mobility')
  lines(mobility$mob_combined_smooth$dates,mobility$mob_combined_smooth[,i+1],col='blue')
  # lines(mob3[,i+1],col='red')
  abline(h=1,lwd=2,col='red',lty=2)
}
```



## process Epi data

load Epi data and serial interval
```{r, echo = FALSE}
## # serial interval estimate used: mean = 3.96, sd =  4.75
## # Teunis et al.

SI <- list()

for (si in c(1,2)){
  
  SI[[si]] <- list()
  SI[[si]]$si_mean <- d$si_mean[si]
  SI[[si]]$si_std <- d$si_std[si]
  
  SI[[si]]$SI <- gamma_dist_EpiEstim(si_mu =  d$si_mean[si], 
                            si_std  = d$si_std[si], 
                            SItrunc = 30)
  
  plot(seq(0, SI[[si]]$SI$SItrunc), SI[[si]]$SI$dist, type = "h",
       lwd = 10, lend = 1, xlab = "time (days)", ylab = "frequency")
  title(main = "Discrete distribution of the serial interval of COVID-19")
  
}

```

## delay infection to death

```{r, echo = FALSE}

delta_id <- gamma_dist_EpiEstim(si_mu = mu_id , 
                                si_std  = .45*mu_id, 
                                SItrunc = 50)

plot(seq(0, delta_id$SItrunc), delta_id$dist, type = "h",
     lwd = 10, lend = 1, xlab = "time (days)", ylab = "frequency")
title(main = "Discrete distribution of the delay infection to death")

sum(delta_id$dist[1:7])


```

# Useful formatting

see paper

```{r}

# delay death infection matrix
H <- matrix(0,nrow = N_days, ncol = N_days)
for (i in 1:N_days){
  f <- max(c(1,i-delta_id$SItrunc))
  H[i,f:i] <- rev(delta_id$dist)[((delta_id$SItrunc+1)-(i-f)):(delta_id$SItrunc+1)]
  if (i>1) H[i,f:i] <-  H[i,f:i]/sum( H[i,f:i])
}

# matrix of mobility and delayed version
M <- as.matrix(mobility$mob_combined_smooth[,-1])
# M_D <- H %*% M


# delay SI death to death matrix
W <- list()
Ot <- list()
for (si in c(1,2)){
  
  W[[si]] <- list()
  W[[si]]$W <- matrix(0,nrow = N_days, ncol = N_days)
  for (i in 1:N_days){
    f <- max(c(1,i-SI[[si]]$SI$SItrunc))
    W[[si]]$W[i,f:i] <- rev(SI[[si]]$SI$dist)[((SI[[si]]$SI$SItrunc+1)-(i-f)):(SI[[si]]$SI$SItrunc+1)]
    # if (i>1) H[i,f:i] <-  H[i,f:i]/sum( H[i,f:i])
  }
  
  # overall infectivity matrix
  Ot[[si]] <- list()
  Ot[[si]]$Ot <- W[[si]]$W %*% mD
  # correct infectivity when >0 case observed but no infectivity
  for(i in 1:N_geo){
     Ot[[si]]$Ot[ which( (D[,i+1]>0) & (Ot[[si]]$Ot[,i] ==0 ) ),i] <-NA
  }
}




```

# save output

```{r}

inputs <- list(D = D,
               M = M,
               Ot = Ot,
               W = W,
               H = H,
               SI = SI,
               delta_id = delta_id,
               mob_raw = mobility$mob_raw)

saveRDS(object = inputs, 
        file = paste0(path_s,'inputProcessing/Rdata/',
                      date_week_finishing,'_inputs_from_',D_source,'.rds'))

```