---
title: "input"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)


```

# input data

```{r}
source(file = '../inputProcessing/date_input.r')
source(file = 'Rscript/niceplot.R')



```

## make figure1



```{r}

# for (date_num in length(dates_input)){
date_num = length(dates_input)

date_week_finishing <-  as.Date(dates_input[date_num],format = '%Y-%m-%d')

si <- 2
for (Mdata in c('A','G')){
  # Mdata = 'A'
  
  inputs<- readRDS(file=paste0(
    '../../../../Box Sync/save_research/Mobility.2.0.Save/Saved_file/inputProcessing/Rdata/',
    date_week_finishing,'_inputs_from_',Mdata,'.rds'))
  
  res_base <- readRDS(file=paste0(
    '../../../../Box Sync/save_research/Mobility.2.0.Save/Saved_file/EpiEstim/Rdata/',
    date_week_finishing,'_output_from_',Mdata,'.rds'))
  
  Tb_best <- readRDS(file = paste0('../../../../Box Sync/save_research/Mobility.2.0.Save/Saved_file/TableModels_comparision/RData/',
                                   date_week_finishing,'_output_over_form_',Mdata,'.rds' ))$Tb_best
  
  n_country <- nrow(Tb_best)
  country <- Tb_best$country
  
  for (i in 1:n_country){
    # i=1
    if (Tb_best$change[i] == 'no'){
      Change <- 0
      res_summary <-  readRDS( file = paste0('../../../../Box Sync/save_research/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_Over/Rdata/',
                                             date_week_finishing,'_output2_over_form_',Mdata,'.rds' ) )[[si]]
      
      
    }else{
      Change <- 1
      res_summary <-  readRDS( file = paste0('../../../../Box Sync/save_research/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_tD_Over/Rdata/',
                                             date_week_finishing,'_output2_over_form_',Mdata,'.rds' ) )[[si]]
    }
    
    niceplot(i, res_summary, res_base, inputs)
    
  }
  
}

```
