---
title: "input"
author: "Pierre Nouvellet"
date: "2019-07"
---

```{r options, include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='figs/', fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
)


```

# input data

```{r}
# source(file = '../inputProcessing/date_input.r')
source(file = 'Rscript/niceplot.R')



```

## make figure1



```{r}

inputs<- readRDS(file=
                   '../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/inputProcessing/Rdata/inputs.rds')
names(inputs)
data_stream <- names(inputs$M_process_mat )
# for(i in 1:length(data_stream)){
#   dir.create(path = paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/figure1/figs/',data_stream[i]))
# }


res_base <- readRDS(file = 
                      paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/EpiEstim/Rdata/output_EpiE.rds' ))


si <- 2
for (Mdata in data_stream[1]){
  # Mdata = data_stream[1]
  
  
  
  
  
  res_m <-  readRDS( file = paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_Over/Rdata/output_over_form_',Mdata,'.rds' ))[[si]]
  
  
  res_summary <- readRDS( file = paste0('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/FitModels/R0_beta_Over/Rdata/output2_over_form_',Mdata,'.rds' ) )[[si]]
  
  
  
  n_country <- length(res_m$country)
  country <- res_m$country
  
  country_initial <- names(inputs$D)[-1]
  
  
  for (i in 1:n_country){
    
    k <- which(country_initial %in% country[i])
    Change <- 0
    niceplot(i, res_summary, res_base, inputs)
    
  }
}

```
