---
title: "R0Beta"
author: "Pierre Nouvellet"
date: "2019-07"
output:
  html_document:
    self_contained: no
---

```{r , include = FALSE, message = FALSE, warning = FALSE, error = FALSE}
library(knitr)
library(Hmisc)
library(EpiEstim)
library(zoo)
library(latex2exp)

opts_chunk$set(collapse = TRUE)

opts_chunk$set(fig.path='../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/EpiEstim/figs/', fig.keep='high', 
               dev=c('png'), fig.width=9, fig.height=6, cache=FALSE,
               tidy=FALSE, warning=FALSE, fig.show="asis"
 	       )

```

# input data


```{r}
layout(matrix(1:4,2,2))

d <- readRDS('../../../../Dropbox (SPH Imperial College)/Mobility.2.0.Save/Saved_file/inputProcessing/Rdata/inputs.rds')
names(d)

d_infer <- list()


for (si in 1:2){ # SI
  
  d_infer[[si]] <- list()
  
  for (c in 1:(ncol(d$D)-1)){ #country
    
    # M <- (d$W[[si]]$W)
    # M <- (d$Ot[[si]]$Ot)
    # M <- d$H
    
    # mobility streams
    n_stream <- names(d$M_process_mat)
    M <- matrix(NA,nrow = nrow(d$D),ncol = length(n_stream))
    for(i in 1:length(n_stream)){
      M[,i] <- d$M_process_mat[[i]][,c]
    }
    colnames(M) <- n_stream
    M_tim <- M[,-which(colSums(!is.na(M)) == 0)]
    
    d_i <- list(D = d$D[,c(1,c+1)],
                Ot = d$Ot[[si]]$Ot[,c],
                W = d$W[[si]]$W,
                H = d$H,
                M = M,
                M_tim = M_tim)
    
    ######################################
    
    # allowed changes in relationship and week with inference
    # c("2020-03-02","2020-04-06","2020-05-04","2020-06-01","2020-07-06")
    allowed_change <- c("2020-03-02","2020-04-06","2020-05-04","2020-06-01","2020-07-06")
    
    
    weekly_D <- colSums(matrix(d_i$D[,2],nrow = 7,ncol = nrow(d_i$D)/7, byrow = FALSE))
    day_start_week <- d_i$D$dates[seq(1,length( d_i$D$dates),by=7)]
    if(si==1) {
      plot(weekly_D,main = names(d$D)[c+1])
      abline(h=10,lty = 2, col='red3')
    }
    thresholds_death <- seq(which(weekly_D > 10)[1],tail(which(weekly_D > 10),1))
    if(length(thresholds_death)>12){
      possible_change <- thresholds_death[-c(seq(1,4),
                                             seq(length(thresholds_death)-7,
                                                 length(thresholds_death)))]
      f <- which(as.character(day_start_week[possible_change]) %in% allowed_change)
      possible_change <- day_start_week[possible_change[f]]
      # if(length(f)==0){
      #   possible_change <- thresholds_death[-c(seq(1,8),
      #                                        seq(length(thresholds_death)-7,
      #                                            length(thresholds_death)))]
      #   f <- which(as.character(day_start_week[possible_change[1]]-7) %in% allowed_change)
      #   possible_change <- day_start_week[possible_change[f]] - 7
      # }
    }else{
      possible_change <- ''
    }
    F_more10D <- as.numeric(rep(weekly_D > 10,each = 7))
    
    d_i$F_more10D <- F_more10D
    d_i$possible_change <- possible_change
    
    d_infer[[si]][[names(d$D)[c+1]]] <- d_i
  }
}

```
 check
 
 
```{r}
 
for (i in 1:(ncol(d$D)-1)){
  if( length(d_infer[[1]][[i]]$possible_change) > 1){
    temp <- paste0(d_infer[[1]][[i]]$possible_change,collapse = ', ')
  }else{
   temp <- d_infer[[1]][[i]]$possible_change
  }
  print(paste0(i,' - ',names(d_infer[[1]])[i],' : ', temp ))
}
 
```
